# Generated by Django 4.0.6 on 2022-07-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_imageabout_alt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
