# Generated by Django 4.0.6 on 2022-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_socials_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
